<?php
// Any PHP logic here (if needed)
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <title>About Meditational | Free Online Meditation Timer with Interval Bells</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="Meditational is a free online meditation timer with interval bells, background nature sounds, and a minimalist interface. No ads, no sign-up." />
    <meta name="robots" content="index, follow" />
    <link rel="canonical" href="https://meditational.space/about" />
    <link rel="stylesheet" href="style.css" />
</head>

<body class="scroll">
    <!-- ... your HTML content ... -->
    <footer class="scroll">
        <p><a class="link" href="/">Back to Timer</a></p>
        <p>© 2025 Meditational.space</p>
    </footer>
</body>

</html>
<?php
echo "<!-- This page is generated by PHP. -->";
?>